
BoxLayout:
		orientation: 'vertical'
		padding: 20 
		spacing: 10 
		rows: 10
		resultButtons:
				text: "test"
		resultButtons:
				text: "test"
		resultButtons:
				text: "test"
		resultButtons:
				text: "test"
		resultButtons:
				text: "test"
		resultButtons:
				text: "test"
		resultButtons:
				text: "test"
		resultButtons:
				text: "test"
		resultButtons:
				text: "test"
		resultButtons:
				text: "test"

				